language: node_js
cache: yarn
node_js:
  - 10
  - 12
os:
  - linux
  - osx
  - windows
matrix:
  fast_finish: true
  allow_failures:
    - os: windows
install:
  - npm install --global yarn lerna
  - lerna bootstrap
  - lerna exec -- yarn link
script:
  - cd ..
  - mkdir wcf-test
  - cd wcf-test
  - wcf
  - wcf start --author test --copyrightOwner test --license MIT
  - wcf factory --humanName test --description test --name test --orgNpm @test --orgGit test --gitRepo git@github.com:test/test.git
  - wcf element --customElementTemplate Slim --name slim-test --description test --no-addProps --no-useSass
  - wcf element --customElementTemplate Polymer --name polymer-test --description test --no-addProps --no-useSass
  - wcf element --customElementTemplate Vanilla --name vanilla-test --description test --no-addProps --no-useSass
  - cd factories/test
  - lerna run build
